export const asyncStatus = {
    IDLE: "idle",
    LOADING: "loading",
    SUCCEEDED: "succeeded",
    ERROR: "error",
};


export const type_constant = {
    // Disease
    ADD_DISEASE: "ADD_DISEASE",
    GET_DISEASE: "GET_DISEASE",
    EDIT_DISEASE: "EDIT_DISEASE",
    DELETE_DISEASE: "DELETE_DISEASE",
    LOGIN: "LOGIN",
    CHECK_AUTH: "CHECK_AUTH",
    FETCH_PMID_ARTICLES: "FETCH_PMID_ARTICLES",
    ADD_BIO_MARKER: "ADD_BIO_MARKER",
    UPDATE_BIO_MARKER: "UPDATE_BIO_MARKER",
    GET_BIO_MARKER: "GET_BIO_MARKER",
    GET_BIO_MARKER_HANDLING: "GET_BIO_MARKER_HANDLING",
    APPROVE_REJECT_BIO_MARKER_HANDLING: "APPROVE_REJECT_BIO_MARKER_HANDLING",
    ADD_SPECIE: "ADD_SPECIE",
    ADD_STUDY_TYPE: "ADD_STUDY_TYPE",
    ADD_RESEARCH_TYPE: "ADD_RESEARCH_TYPE",
    ADD_ORGANS: "ADD_ORGANS",
    ADD_SYSTEMS: "ADD_SYSTEMS",
    ADD_METHODS: "ADD_METHODS",
    GET_SPECIE: "GET_SPECIE",
    GET_STUDY_TYPE: "GET_STUDY_TYPE",
    GET_RESEARCH_TOPIC: "GET_RESEARCH_TOPIC",
    GET_ORGANS: "GET_ORGANS",
    GET_SYSTEMS: "GET_SYSTEMS",
    GET_METHODS: "GET_METHODS",
    GET_COUNTRY: "GET_COUNTRY",
    ADD_COUNTRY: "ADD_COUNTRY",
    EDIT_SPECIE: "EDIT_SPECIE",
    GET_ROLE: "GET_ROLE",
    ADD_ROLE: "ADD_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    EDIT_ROLE: "EDIT_ROLE",
    DELETE_SPECIE: "DELETE_SPECIE",
    // Article
    ADD_ARTICLE: "ADD_ARTICLE",
    DELETE_ARTICLE: "DELETE_ARTICLE",
    UPDATE_ARTICLE_STATUS: "UPDATE_ARTICLE_STATUS",
    GET_ARTICLE: "GET_ARTICLE",
    GET_DASHBOARD_DATA: "GET_DASHBOARD_DATA",
    // User
    ADD_USER: "ADD_USER",
    GET_USERS: "GET_USERS",
    DELETE_USER: "DELETE_USER",
    EDIT_USER: "EDIT_USER",


}


export const save_tokens_constant = {
    AUTH: "auth"
}